POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "My Second Blog Post from Tuan Anh",
  "author": "Anh",
  "url": "https://example.com/anh",
  "likes": 9,
  "userId": "6493b464e62d347a2ae5177c"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Blog Post 3 from Random User",
  "author": "Random User",
  "url": "https://example.com/random3",
  "likes": 8
 }

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoYW5oIiwiaWQiOiI2NDkzYjU3ZmU2MmQzNDdhMmFlNTE3OGMiLCJpYXQiOjE2ODc0NTA4OTV9.asllYs0cp81BHeCrMgWMEm4DKv8HTqJ-Wlx3u0ZBJ5A

{
  "title": "Quoc Khanh 222",
  "author": "Quoc Khanh",
  "url": "https://example.com/quockhanh2",
  "likes": 6
 }

 
